create table tree_analysis(
 tree_id int PRIMARY KEY,
  block_id int,
  created_at date,
  tree_dbh int,
  stump_diam int,
  curb_loc boolean,
  status varchar,
  health varchar,
  spc_latin varchar,
  spc_common varchar,
  steward varchar,
  guards varchar,
  sidewalk varchar,
  user_type varchar,
  problems varchar,
  root_stone boolean,
  root_grate boolean,
  root_other boolean,
  trunk_wire boolean,
  trnk_light boolean,
  trnk_other boolean,
  brch_light boolean,
  brch_shoe boolean,
  brch_other boolean,
  address varchar,
  postcode int,
  zip_city varchar,
  community_board int,
  borocode int,
  borough varchar,
  cncldist int,
  st_assem int,
  st_senate int,
  nta varchar,
  nta_name varchar,
  boro_ct int,
  state varchar,
  latitude  numeric,
  longitude numeric,
  x_sp numeric,
  y_sp numeric,
  council_district numeric,
  census_tract numeric,
  bin numeric,
  bbl numeric
);
--конечно зависит от целей проекта, предполагаю, что искать надо по местоположению, поэтому так
CREATE INDEX ON tree_analysis ((lower(zip_city)));